import { useState } from 'react'
import toast from 'react-hot-toast'
import { BrainCircuit, Sparkles } from 'lucide-react'
import { careerAPI } from '../api/client'
import Loader from '../components/Loader'
export default function Interview(){
 const [role,setRole]=useState('AI/ML Engineer'),[difficulty,setDifficulty]=useState('medium'),[data,setData]=useState(null),[loading,setLoading]=useState(false)
 const run=async()=>{setLoading(true);try{setData((await careerAPI.interview({role,difficulty})).data);toast.success('Interview set generated.')}catch(e){toast.error(e.response?.data?.detail||'Could not generate interview.')}finally{setLoading(false)}}
 return <div className="space-y-6 animate-fade-in"><div className="flex items-center gap-2"><BrainCircuit className="text-ibm-cyan"/><div><h1 className="text-2xl font-bold text-ibm-white">Mock Interview</h1><p className="text-ibm-gray-4 mt-1">Generate role-specific questions using your CareerTwin profile.</p></div></div><div className="card grid md:grid-cols-3 gap-4"><div className="md:col-span-2"><label className="label">Target role</label><input className="input" value={role} onChange={e=>setRole(e.target.value)}/></div><div><label className="label">Difficulty</label><select className="input" value={difficulty} onChange={e=>setDifficulty(e.target.value)}><option>easy</option><option>medium</option><option>hard</option></select></div><button className="btn-primary md:col-span-3 flex items-center justify-center gap-2" disabled={loading} onClick={run}>{loading?<><span className="animate-spin">◌</span>Generating…</>:<><Sparkles size={15}/>Generate interview</>}</button></div>{loading&&<Loader text="Gemini is preparing your interview…"/>}{data?.questions&&<div className="space-y-4">{data.questions.map((q,i)=><div className="card" key={i}><div className="flex justify-between gap-3"><h2 className="font-semibold text-ibm-white">Q{i+1}. {q.question}</h2><span className="badge badge-blue">{q.type}</span></div><p className="text-xs text-ibm-gray-4 mt-3">Good answer should cover: {q.what_good_answer_should_cover}</p><p className="text-sm text-ibm-cyan mt-2">Follow-up: {q.follow_up}</p></div>)}<div className="card"><h2 className="font-semibold text-ibm-white mb-3">Preparation tips</h2><ul className="list-disc pl-5 text-sm text-ibm-gray-4 space-y-2">{data.preparation_tips?.map((x,i)=><li key={i}>{x}</li>)}</ul></div></div>}</div>
}
