import { useState, useEffect } from 'react'
import { careerAPI } from '../api/client'
import { SectionCard, SkillTag, EmptyState } from '../components/Cards'
import ProgressBar from '../components/ProgressBar'
import Loader from '../components/Loader'
import { Map, Award, TrendingUp, DollarSign, Briefcase, Rocket } from 'lucide-react'
import toast from 'react-hot-toast'

export default function Roadmap() {
  const [roadmap,   setRoadmap]  = useState(null)
  const [loading,   setLoading]  = useState(false)
  const [fetching,  setFetching] = useState(true)

  useEffect(() => {
    careerAPI.getRoadmap()
      .then(r => setRoadmap(r.data))
      .catch(() => {})
      .finally(() => setFetching(false))
  }, [])

  const handleGenerate = async () => {
    setLoading(true)
    try {
      const res = await careerAPI.runRoadmap()
      setRoadmap(res.data)
      toast.success('Career roadmap generated by Gemini AI!')
    } catch (err) {
      toast.error(err.response?.data?.detail || 'Failed to generate roadmap. Set your career goals in Profile first.')
    } finally {
      setLoading(false)
    }
  }

  if (fetching) return <Loader text="Loading your career roadmap…" />

  return (
    <div className="space-y-8 animate-fade-in">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-ibm-white">Career Roadmap</h1>
          <p className="text-ibm-gray-4 mt-1">Your personalised path from where you are to where you want to be.</p>
        </div>
        <button onClick={handleGenerate} className="btn-primary flex items-center gap-2" disabled={loading}>
          {loading ? <><div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />Generating…</> : <><Rocket size={15} />Generate Roadmap</>}
        </button>
      </div>

      {loading && <Loader text="Gemini AI is building your roadmap…" />}

      {!roadmap && !loading && (
        <EmptyState
          icon={Map}
          title="No roadmap yet"
          description="Make sure you've set your career goals in your Profile, then click Generate Roadmap."
          action={<button onClick={handleGenerate} className="btn-primary">Generate Roadmap</button>}
        />
      )}

      {roadmap && !loading && (
        <div className="space-y-6 animate-slide-up">
          {/* Journey banner */}
          <div className="card bg-gradient-to-r from-ibm-blue/20 to-ibm-purple/20 border-ibm-blue/30">
            <div className="flex flex-col md:flex-row items-center gap-6">
              <div className="text-center flex-1">
                <p className="text-xs text-ibm-gray-4 mb-1">Starting Point</p>
                <p className="text-lg font-bold text-ibm-white">{roadmap.current_position}</p>
              </div>
              <div className="flex-shrink-0">
                <div className="flex items-center gap-1">
                  {[...Array(5)].map((_, i) => (
                    <div key={i} className="w-6 h-0.5 bg-ibm-blue" />
                  ))}
                  <Rocket size={18} className="text-ibm-blue" />
                </div>
                <p className="text-xs text-ibm-gray-4 text-center mt-1">{roadmap.timeline_months} months</p>
              </div>
              <div className="text-center flex-1">
                <p className="text-xs text-ibm-gray-4 mb-1">Target Position</p>
                <p className="text-lg font-bold text-ibm-cyan">{roadmap.target_position}</p>
              </div>
            </div>
          </div>

          {/* Stats row */}
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            <div className="card text-center">
              <p className="text-2xl font-bold text-ibm-blue">{roadmap.timeline_months}</p>
              <p className="text-xs text-ibm-gray-4 mt-1">Months Timeline</p>
            </div>
            <div className="card text-center">
              <p className="text-2xl font-bold text-ibm-green">{roadmap.required_skills?.length ?? 0}</p>
              <p className="text-xs text-ibm-gray-4 mt-1">Skills Required</p>
            </div>
            <div className="card text-center">
              <p className="text-2xl font-bold text-ibm-purple">{roadmap.certifications?.length ?? 0}</p>
              <p className="text-xs text-ibm-gray-4 mt-1">Recommended Certifications</p>
            </div>
            <div className="card text-center">
              <p className="text-lg font-bold text-ibm-yellow">{roadmap.expected_salary || '–'}</p>
              <p className="text-xs text-ibm-gray-4 mt-1">Expected Salary</p>
            </div>
          </div>

          {/* Required Skills */}
          <SectionCard title="Required Skills" icon={TrendingUp}>
            <div className="flex flex-wrap">
              {roadmap.required_skills?.map(s => <SkillTag key={s} skill={s} variant="new" />)}
            </div>
          </SectionCard>

          {/* Monthly Goals Timeline */}
          <SectionCard title="Monthly Milestones" icon={Map}>
            <div className="space-y-4">
              {roadmap.monthly_goals?.map((goal, i) => (
                <div key={i} className="flex gap-4">
                  <div className="flex flex-col items-center">
                    <div className="w-9 h-9 rounded-full bg-ibm-blue/20 border-2 border-ibm-blue flex items-center justify-center text-xs font-bold text-ibm-blue flex-shrink-0">
                      M{typeof goal === 'object' ? goal.month : i + 1}
                    </div>
                    {i < (roadmap.monthly_goals.length - 1) && <div className="w-0.5 flex-1 bg-ibm-gray-3 mt-2 min-h-[32px]" />}
                  </div>
                  <div className="bg-ibm-gray-2 rounded-lg p-4 flex-1 mb-4 border border-ibm-gray-3">
                    <p className="text-sm font-semibold text-ibm-white">{typeof goal === 'object' ? goal.goal : goal}</p>
                    {typeof goal === 'object' && (
                      <>
                        {goal.milestone && <p className="text-xs text-ibm-cyan mt-1">{goal.milestone}</p>}
                        {goal.skills && <div className="flex flex-wrap mt-2">{goal.skills.map(s => <SkillTag key={s} skill={s} variant="default" />)}</div>}
                      </>
                    )}
                  </div>
                </div>
              ))}
            </div>
          </SectionCard>

          {/* Recommended Certifications */}
          {roadmap.certifications?.length > 0 && (
            <SectionCard title="Recommended Certifications" icon={Award}>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                {roadmap.certifications.map((cert, i) => (
                  <div key={i} className="bg-ibm-gray-2 rounded-lg p-4 border border-ibm-purple/30 hover:border-ibm-purple transition-colors">
                    <p className="text-sm font-semibold text-ibm-white">{typeof cert === 'object' ? cert.name : cert}</p>
                    {typeof cert === 'object' && cert.relevance && <p className="text-xs text-ibm-gray-4 mt-1">{cert.relevance}</p>}
                    {typeof cert === 'object' && cert.url && (
                      <a href={cert.url} target="_blank" rel="noopener noreferrer" className="text-xs text-ibm-cyan hover:underline mt-2 inline-block">View Certification →</a>
                    )}
                  </div>
                ))}
              </div>
            </SectionCard>
          )}

          {/* Future Scope */}
          {roadmap.future_scope && (
            <SectionCard title="Future Growth Opportunities" icon={Rocket}>
              <p className="text-sm text-ibm-white leading-relaxed">{roadmap.future_scope}</p>
            </SectionCard>
          )}
        </div>
      )}
    </div>
  )
}
